# Generated by Django 4.2.16 on 2026-05-24 12:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin')], default='analyst', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('row_count_total', models.IntegerField(default=0)),
                ('row_count_ok', models.IntegerField(default=0)),
                ('row_count_error', models.IntegerField(default=0)),
                ('row_count_warning', models.IntegerField(default=0)),
                ('error_summary', models.JSONField(default=list)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('warning', 'Warning')], default='ok', max_length=10)),
                ('parse_errors', models.JSONField(default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='api.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='api.tenant')),
            ],
            options={
                'ordering': ['job', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP — Fuel Combustion'), ('sap_procurement', 'SAP — Procurement'), ('utility_electricity', 'Utility — Electricity'), ('travel_flight', 'Travel — Flight'), ('travel_hotel', 'Travel — Hotel'), ('travel_ground', 'Travel — Ground Transport')], max_length=30)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 — Direct'), ('2', 'Scope 2 — Purchased Energy'), ('3', 'Scope 3 — Value Chain')], max_length=1)),
                ('category', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('location_raw', models.CharField(blank=True, max_length=255)),
                ('location_resolved', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('quantity_original', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_original', models.CharField(max_length=20)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_normalized', models.CharField(max_length=20)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('emission_factor_source', models.CharField(max_length=100)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged — Needs Attention')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reasons', models.JSONField(default=list)),
                ('is_edited', models.BooleanField(default=False)),
                ('original_values', models.JSONField(default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized', to='api.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='api.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.tenant')),
            ],
            options={
                'ordering': ['-activity_date', 'scope', 'source_type'],
            },
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('locked', 'Locked for Audit')], max_length=20)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.normalizedrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.tenant')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=20)),
                ('plant_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='api.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='api_normali_tenant__5b7ede_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'scope'], name='api_normali_tenant__c6d2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'activity_date'], name='api_normali_tenant__d1b9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'is_suspicious'], name='api_normali_tenant__fe9a24_idx'),
        ),
    ]
